version: '3.9'

services:
  main-machine:
   build: ./main_machine
   container_name: main_server_machine
   ports:
    - 5001:80
   networks:
    - db_network
    - client_network
  
  ubuntu-machine:
   build: ./ubuntu_machine1
   container_name: ubuntu_client_machine1
   networks:
    - client_network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: master
      POSTGRES_PASSWORD: mypassword
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"     
    volumes:
      - 
        type: bind
        source: /tmp/postgresql/data
        target: /var/lib/postgresql/data
    networks:
      - db_network

networks:
  db_network:
  client_network:


