version: '3.9'

services:
  main-service:
   depends_on:
    one-shot-service:
     condition: service_completed_successfully
   build: ./main_machine
   container_name: main_server_machine
   ports:
    - 5001:80
   networks:
    - db_network
    - client_network
  
  one-shot-service:
   depends_on:
    postgresql-service:
     condition: service_healthy
   build: ./one_shot_machine
   container_name: one_shot_container
   networks:
    - db_network
    - client_network
  
  ubuntu-service:
   build: ./ubuntu_machine1
   container_name: ubuntu_client_machine1
   networks:
    - client_network

  postgresql-service:
    build: ./database_machine
    container_name: postgresql_machine
    healthcheck:
      test: find /var/lib/postgresql/data -iname pgdata || exit 1
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    restart: always
    ports:
      - "5433:5432"     
    volumes:
      - 
        type: bind
        source: /home/tmp/postgresql/data
        target: /var/lib/postgresql/data
    networks:
      - db_network

networks:
  db_network:
  client_network:


