version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  
  postgresql-service:
    build: ./docker/postgres
    container_name: postgresql_machine
    healthcheck:
      test: find /var/lib/postgresql/data -iname pgdata || exit 1
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    restart: always
    ports:
      - "5433:5432"     
    volumes:
      - 
        type: bind
        source: /home/tmp/postgresql/data
        target: /var/lib/postgresql/data
  
  ubuntu-service:
   build: ./docker/ubuntu1
   container_name: ubuntu_client_machine1